# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2c79cf18b6921d662b79acb80b550c7d576ff02b196feec680d8f7afa9c631d72fc54b4009a37ab05b4866fc3ccb0e70bc3c7fbfc5e58576cd9600ebf7014fee

test:
  secret_key_base: 6d2bf7770127b515ba1ef11dbdb2e12a6ea51eef4b147d9186b02820569e6c42e96ac47a780186396d710b91280943ce0dc055e8fe344fa9b1530c8f535e3d43

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
